### ISSUE TITLE
Parse

### ISSUE THREAD

**Issue by LizaFeng** [KJohnson-prof/Steal-tastic0.3#1]
1. I didn't get an email for the back4app so I can't view the database. 
2.  Did we set up parse sdk yet? (like connect it to our app) Is someone working on that?

**Comment by KJohnson-prof** [comment]
1) Which email did you use to register for back4app? It says "Waiting For Account Registration" next to your email. In the mean time I can export a json file for you. It will be in our repo
2) I already connected the app to the server so you don't have to worry about that
